language: node_js
node_js:
- '4'
env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - secure: T6COWtRRjYurQeqyWhgO8lp03XRSW51dACf7YqcKNsVQ8wf75029//G26d+tyNhGt4CsPtYye6iTixmDJ/PhsRYvrCgGQj3OWVcHGEQ9DqfeqNBd4KFUT/1r1c+FU0nqXV4/vsZRqx0AM7LVfH7nmt5c8E0HgVNUQqsi1QGRss1ZNUBZZSx1T1/Xq3k5fAhYn6Qkn4VRCSMWxZyKl6gKigc+madEPO8MtNkFaixWTLboTS5QN7110QHltUmYfrC1bOjZYxqYCDXRdgFvqSx0NoIZIDbnmITnHgFNBYXImyP37UfJbc8RhACGZQdBe76pvav4x6n+TonTn8pA24QL9Vkf9NC+vtIsU9JkOPsoNx3YtZGzBAhQMK4CWHa+08N24yND3Ye37sNsLObtrckuM3E/PVjaolpWA0upaEkFD0t6H5oR/RgQiXXN3oBXrKvAkztsoOdnfMQk1Tnep4v7fZzv0SN4SOpp3Wz+la7Qg69fNO9/Or42mexcrhDFr4CU7bOsHj+RUvdWSGS5QN72qFXG+T/Lu5jf1Xg3hjI2L5iPAF+nGA9DSvi+0gx4xLvQ1zNvtPlLxKkDRqDdG0C4PQ3d+PD2XOK8ojpvBZBmQUNGe4xBBH8Mk7n08r+XeXrYqgMtuvky3LWsYzd0JXx3fUz0S+dEDLdF+oFG7qUbfvQ=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  apt: true
  directories:
  - node_modules
before_install:
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh
before_script:
- "./.build_scripts/lint.sh"
- npm test
script:
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: ".build_scripts/deploy.sh"
  on:
    branch: "${DEPLOY_BRANCH}"
