language: node_js
node_js:
- '4'
env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  secure: "YUDra0/Jb70TIOV7fLELDglRugA3Zy8vu8SsGA4+Ou30bMzqKyBOdr5089dJ0v3iP0NDOCb6PalhiDtnCG8huFQ5UoF5lFLAFaqagxPw2APaVsCnmVlxK1GAic6eRP4XNwHG/D2os7/qcUbge5sXT+sN0Houn/1UOqI1QYOQkaQkZC+J6f/wchUWSCrZRGjOf05F5d9rHE03obL7cXpxQQO8vmB9fpq3799YUy1mer12IuhsVdiADAgFyPJI5m36LcD4OP9qIquQitRFttGsWfmyIACpLaSyLg8zWFDIh62t2A/1YlK2fnafrbDA5cH0aOvxWqsbCUaVuynZMgpasNYpyhcCL3YgpqMYM1xZA/fQfCrldmxnF3SCBDJlJiHa7MBWl8ATH3B6aJnbBudpnezoAz8EmHLR8TQ0+Ai+AcdZO3Nj38HjDyVwx1g0B7RGq/QVtxluCC9GzOhJrjPNyvYpjALQpPB7YG2NgOlTJonmvxPgy9rw45Os01j4frL1M1Gpv9JpAst8pm5aLf6WwIo1elr+tLE0vcI1Qj6LcOvV4u1ye77ooYM6mqVRQjd1PCPXHabIf2ESTBeCHNs3STkLdnMlw9h05ofm92aLv3glLaFMUMUy9kjAso9ryS8t4MOS/SvBnfkW3++Sm88kFqZa0qxV9nRE2pH+2tUVtss="
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  apt: true
  directories:
  - node_modules
before_install:
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh
before_script:
- "./.build_scripts/lint.sh"
- npm test
script:
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: ".build_scripts/deploy.sh"
  on:
    branch: "${DEPLOY_BRANCH}"
