language: node_js
node_js:
- '4'
env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - secure: cTL9NaDTJ5GxzAOH4cWEvEz/av7Wii0thGnnrk1gu0QRKjg8RkrC+PLu45OHi+onqaDlNNtoGgGZMHm9nfjXOTXGj3AxG9YCNG/Tp21CTaBJdTN3qz3kxMkkM3XrsjmFpkFmdxuLKWdKCsf3OyYPaUmTRISyxETDhuW1VNkEAulhvtdRBGKkP1TnyHVDd4TXxqF6MSqhxjYQoQjReoQGGkI2z9Tf6MKbsMjIoa31OobIKPbwTuHGN01diakvldCcDXnrX8Sly8E2xoDo/V0o0Dhto1loGVPEOahvqG4eFCNdil2Hyf6UJT7RWvxDZSN+r8BrWoriksBg1e6lLZohulHBq2NfhrbF0eeFIsvtxPuGlRKcrkTi3mzqshud7EKtZisqd44fK9TbxUCXHD1MNkSAHr/ZB3sqlQ8Bqc7FOVU5QSqxxJ/1NeX0Y+p46EeFWI/oSoEA/SpI9vmg8EUqK96d3qUD6qpddsgEmwRdnsQjyR7+DL4a8Sh6vP1MCFoafZ138Xk/1c8V7ykxYMfpbCiB0QMbj9VqFwaMQ3ve2YHHgJGtCpP70Yl7eBmFm2LqOQAWaCplAzPqCS71a0amXnaqHDF7Fo8G+sO49X7bU94IvUQLZq3XQkaJxNAUtwj0EM5lGre1ayaqTBJd0ZdLRMRMtsZtzeZuH/UKsbBRfDI=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  apt: true
  directories:
  - node_modules
before_install:
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh
before_script:
- "./.build_scripts/lint.sh"
- npm test
script:
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: ".build_scripts/deploy.sh"
  on:
    branch: "${DEPLOY_BRANCH}"
